"""Add Timeline column to momo_family table

Revision ID: dfa9b39df58d
Revises: 
Create Date: 2023-11-27 20:01:57.000820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa9b39df58d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('momo_family',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Birthdate', sa.String(length=10), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('Father', sa.String(length=255), nullable=True),
    sa.Column('Mother', sa.String(length=255), nullable=True),
    sa.Column('ImageUrl', sa.String(length=255), nullable=True),
    sa.Column('Gallery', sa.JSON(), nullable=True),
    sa.Column('Bio', sa.JSON(), nullable=True),
    sa.Column('Timeline', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('momo_family')
    # ### end Alembic commands ###
